// <auto-generated />
using System;
using HastaneBilgiSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HastaneBilgiSistemi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200510155242_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "4648aa73-e422-40f5-9f78-f676776be6a0",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "cfe87cb9-0131-44e4-b36d-b6f4d060e1cc",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "b8ee632c-4da9-4ad7-8e1b-ceb5754c8a90",
                            Name = "Secretary",
                            NormalizedName = "SECRETARY"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "50f7c5b3-1c61-4b33-b8f7-65dc60957841",
                            Name = "Patient",
                            NormalizedName = "PATIENT"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "b134deab-1ede-4e1f-8585-39d64498433e",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            FullName = "Admin Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "admin@admin.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEJBPowIQK9FJFbu3O/Zye4ahwaNzQifOIypTX24C/MV+Gfqol6rWqHLZu54zFkcdPA==",
                            PhoneNumber = "5325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4c685e19-962c-4270-9996-fd90226bd799",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "bac232c1-a40b-4e21-acb9-bd331c8cd72a",
                            Email = "doctor@doctor.com",
                            EmailConfirmed = true,
                            FirstName = "Rıfat",
                            FullName = "Rıfat Yaşar",
                            LastName = "Yaşar",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@DOCTOR.COM",
                            NormalizedUserName = "doctor@doctor.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEE4Bb8boopXkoLMmScRxB1HN6B4s2nOejEwnNwOHHP252r/MITtD82PXxdIzO1syJw==",
                            PhoneNumber = "5325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6c9fd469-b2b6-4f5a-aaea-6dd806a0196b",
                            TwoFactorEnabled = false,
                            UserName = "doctor@doctor.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "892ce7ec-8772-4e58-aae6-6674c716d4de",
                            Email = "secretary@secretary.com",
                            EmailConfirmed = true,
                            FirstName = "Ayşe",
                            FullName = "Ayşe Gül",
                            LastName = "Gül",
                            LockoutEnabled = false,
                            NormalizedEmail = "SECRETARY@SECRETARY.COM",
                            NormalizedUserName = "secretary@secretary.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKVjjnfQdlOZc/xHz/ONRoyxCcZGdlaQEFlktRhm9FPzhyMWHGFzhv30ZiCf81SjRQ==",
                            PhoneNumber = "5325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "63ececb7-2bcb-4c87-b80e-709ee6bc303e",
                            TwoFactorEnabled = false,
                            UserName = "secretary@secretary.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "66607af6-0659-4396-a9cb-4e7e99ea5281",
                            Email = "patient@patient.com",
                            EmailConfirmed = true,
                            FirstName = "Osman",
                            FullName = "Osman Oduncu",
                            LastName = "Oduncu",
                            LockoutEnabled = false,
                            NormalizedEmail = "PATIENT@PATIENT.COM",
                            NormalizedUserName = "patient@patient.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKO/vwPz3H1fzbWhjL9F52yZNd94wNnigH5zmXfmfdvKFWM7aPfSzUYss7ekN3N1bg==",
                            PhoneNumber = "5325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15c158ad-9aab-4046-957d-196e7fccd430",
                            TwoFactorEnabled = false,
                            UserName = "patient@patient.com"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Diseas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Diseas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "COVID-19"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hipertansiyon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hiperlipidemi "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Akut Romatizmal Ateş"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Multiple Skleroz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Üst Solunum Yolu Enfeksiyonu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alt Solunum Yolu Enfeksiyonu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Akut Gastroenterit"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Yumuşak Doku Enfeksiyonu "
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolyclinicId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PolyclinicId = 9,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AZOSİLİN 30 TB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BACTRİM 200/40 MG 100 ML SÜSPANSİYON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DUOCİD ORAL SÜSPANSİYON 250MG/5ML 100ML"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DEPOSİLİN 1.2 IU FLK"
                        },
                        new
                        {
                            Id = 5,
                            Name = "MACROL 250 MG 100 ML SUSPANSIYON"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NİDAZOL 500 MG FİLM TABLET"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SUPRAX SUSPANSIYON 50 ML."
                        },
                        new
                        {
                            Id = 8,
                            Name = "SUPRAX 400 MG"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.PatientHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Complaint")
                        .HasColumnType("nvarchar(512)")
                        .HasMaxLength(512);

                    b.Property<int>("DiseasId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiseasId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PolyclinicId");

                    b.HasIndex("ReservationId");

                    b.ToTable("PatientHistory");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.PatientHistoryMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.Property<int>("PatientHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("PatientHistoryId");

                    b.ToTable("PatientHistoryMedication");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Polyclinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Polyclinic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ağız ve Diş Sağlığı Servisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Anestezi ve Reanimasyon Servisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beslenme ve Diyet Bölümü"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cilt Hastalıkları Servisi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Çocuk Servisi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dahiliye Servisi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fizik Tedavi Servisi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Genel Cerrahi Servisi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Göğüs Hastalıkları Servisi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Göz Servisi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kadın Hastalıkları ve Doğum Servisi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kardiyoloji Servisi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kulak Burun Boğaz Servisi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nöroloji Servisi"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nöroşirüji Servisi"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ortopedi ve Travmatoloji Servisi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Patoloji Servisi"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Psikoloji Servisi"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Radyoloji Servisi"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Üroloji Servisi"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PolyclinicId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Secretary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Secretary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRoleClaim", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserClaim", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserLogin", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserRole", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserToken", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Doctor", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Patient", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.PatientHistory", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Diseas", "Diseas")
                        .WithMany()
                        .HasForeignKey("DiseasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Patient", "Patient")
                        .WithMany("PatientHistories")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.PatientHistoryMedication", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.PatientHistory", "PatientHistory")
                        .WithMany("Medications")
                        .HasForeignKey("PatientHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Reservation", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Secretary", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
