// <auto-generated />
using System;
using HastaneBilgiSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HastaneBilgiSistemi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "662b6721-9581-4458-8187-2dcf2710620f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "178c696b-adb0-4847-958b-470cf33f2b79",
                            Name = "Doctor",
                            NormalizedName = "DOCTOR"
                        },
                        new
                        {
                            Id = 3,
                            ConcurrencyStamp = "eff986c9-bd1f-4b53-8592-935872f4ad38",
                            Name = "Secretary",
                            NormalizedName = "SECRETARY"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "b8b7f8f6-d559-4f94-85f7-a3ce3923f6ea",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "7ba61a2f-dd81-48bf-a184-ffbc3e1d6258",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            FullName = "Admin Admin",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "admin@admin.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEPASut7584avIw5wcIAkBa79LFRtHNOPHrqLDgn5cS3ZpZU7O6k5AyyWhYY692TZHA==",
                            PhoneNumber = "+905325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7b2f62a-41b4-47ff-9ac4-668d5ef72569",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "22497238-0e62-4ad0-9bac-a83c88373ce5",
                            Email = "doctor@doctor.com",
                            EmailConfirmed = true,
                            FirstName = "Rıfat",
                            FullName = "Rıfat Yaşar",
                            LastName = "Yaşar",
                            LockoutEnabled = false,
                            NormalizedEmail = "DOCTOR@DOCTOR.COM",
                            NormalizedUserName = "doctor@doctor.com",
                            PasswordHash = "AQAAAAEAACcQAAAAECudSbSrZWTmx8lKguysMhBKB2uX6bhyFSZn/Gn7D1cAktG5I2cmvZ+xMpvagLnsYA==",
                            PhoneNumber = "+905325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "097c7d89-d05b-41b1-8d45-064d08ebf687",
                            TwoFactorEnabled = false,
                            UserName = "doctor@doctor.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "a7997f76-4de8-483e-a7ce-33a02f67f807",
                            Email = "secretary@secretary.com",
                            EmailConfirmed = true,
                            FirstName = "Ayşe",
                            FullName = "Ayşe Gül",
                            LastName = "Gül",
                            LockoutEnabled = false,
                            NormalizedEmail = "SECRETARY@SECRETARY.COM",
                            NormalizedUserName = "secretary@secretary.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEA54ACDAHLwEHApgudi9QVXkRCkf9h+o22U276MWqi9dx2l4bkvnrR305nvJz4hwBg==",
                            PhoneNumber = "+905325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e92b13c0-1c42-4c61-be95-2dc04a227054",
                            TwoFactorEnabled = false,
                            UserName = "secretary@secretary.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            BirthDate = new DateTime(1955, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "a114fe38-784e-4b79-af14-c414ce11c811",
                            Email = "client@client.com",
                            EmailConfirmed = true,
                            FirstName = "Osman",
                            FullName = "Osman Oduncu",
                            LastName = "Oduncu",
                            LockoutEnabled = false,
                            NormalizedEmail = "CLIENT@CLIENT.COM",
                            NormalizedUserName = "client@client.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDSgAura8IwJrqQSLnyeTelgceAOl8HH4sDX9VWC0LPi8gHL83vZgdBWoMMHO35suw==",
                            PhoneNumber = "+905325321234",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "252db328-e197-47ed-9e9b-bf2ac23084f6",
                            TwoFactorEnabled = false,
                            UserName = "client@client.com"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserToken", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Client");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ClientHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiseasId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiseasId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PolyclinicId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ClientHistory");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ClientHistoryMedication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientHistoryId");

                    b.HasIndex("MedicationId");

                    b.ToTable("ClientHistoryMedication");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Diseas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Diseas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "COVID-19"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hipertansiyon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Hiperlipidemi "
                        },
                        new
                        {
                            Id = 4,
                            Name = "Akut Romatizmal Ateş"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Multiple Skleroz"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Üst Solunum Yolu Enfeksiyonu"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Alt Solunum Yolu Enfeksiyonu"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Akut Gastroenterit"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Yumuşak Doku Enfeksiyonu "
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PolyclinicId");

                    b.HasIndex("UserId");

                    b.ToTable("Doctor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PolyclinicId = 9,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Medication");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AZOSİLİN 30 TB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BACTRİM 200/40 MG 100 ML SÜSPANSİYON"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DUOCİD ORAL SÜSPANSİYON 250MG/5ML 100ML"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DEPOSİLİN 1.2 IU FLK"
                        },
                        new
                        {
                            Id = 5,
                            Name = "MACROL 250 MG 100 ML SUSPANSIYON"
                        },
                        new
                        {
                            Id = 6,
                            Name = "NİDAZOL 500 MG FİLM TABLET"
                        },
                        new
                        {
                            Id = 7,
                            Name = "SUPRAX SUSPANSIYON 50 ML."
                        },
                        new
                        {
                            Id = 8,
                            Name = "SUPRAX 400 MG"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Polyclinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Polyclinic");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ağız ve Diş Sağlığı Servisi"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Anestezi ve Reanimasyon Servisi"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beslenme ve Diyet Bölümü"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cilt Hastalıkları Servisi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Çocuk Servisi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dahiliye Servisi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fizik Tedavi Servisi"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Genel Cerrahi Servisi"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Göğüs Hastalıkları Servisi"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Göz Servisi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kadın Hastalıkları ve Doğum Servisi"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Kardiyoloji Servisi"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kulak Burun Boğaz Servisi"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Nöroloji Servisi"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nöroşirüji Servisi"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ortopedi ve Travmatoloji Servisi"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Patoloji Servisi"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Psikoloji Servisi"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Radyoloji Servisi"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Üroloji Servisi"
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PolicylinicId")
                        .HasColumnType("int");

                    b.Property<int?>("PolyclinicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PolyclinicId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Secretary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Secretary");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationRoleClaim", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserClaim", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserLogin", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserRole", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ApplicationUserToken", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Client", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ClientHistory", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Diseas", "Diseas")
                        .WithMany()
                        .HasForeignKey("DiseasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.ClientHistoryMedication", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ClientHistory", "ClientHistory")
                        .WithMany()
                        .HasForeignKey("ClientHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Doctor", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Reservation", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneBilgiSistemi.Data.Model.Polyclinic", "Polyclinic")
                        .WithMany()
                        .HasForeignKey("PolyclinicId");
                });

            modelBuilder.Entity("HastaneBilgiSistemi.Data.Model.Secretary", b =>
                {
                    b.HasOne("HastaneBilgiSistemi.Data.Model.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
